import { Inter } from 'next/font/google';

import StyledComponentsRegistry from './lib/registry';
import './globals.css';
import { Container } from './styles/container';
import Sidebar from './components/sidebar';
import SearchBar from './components/search-bar';
import PageTitle from './components/page-title';
import { Main } from './styles/main';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Container>
            <PageTitle text='Pokemon' />
            <SearchBar />
            <Sidebar />

            <Main>{children}</Main>
          </Container>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
